apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ci-droid
  annotations:
    github.com/project-slug: rahul-ratra/ci-droid
spec:
  type: other
  lifecycle: unknown
  owner: rahul-ratra
